title: Power to you
subtitle: ...and me
author: Nawinder Pawar
avatar_url: /assets/img/npawar.png  # Should be 160x160px.
description: > # this means to ignore newlines until "twitter_username:"
  Some thoughts on software and scalability.
repository: nawinderpawar/blog

# contact
contact:
  email: nawinder@pawar.me  # Comment out this line if you don't want to expose your email.
#  url: https://your-contact-url # Uncomment this to provide a contact form url instead of an email

# social links
twitter_username: NawinderPawar
github_username:  nawinderpawar
rss: rss
#linkedin_username: jekyll

# 
# Subscribe Feed
# 
# By default, your site generates a subscription feed (RSS/Atom) at /feed.xml
# Uncomment the next two lines to change the path.
# feed:
#   path: /atom.xml

# If you use a feed publisher such as Feedburner, uncomment the next line
# subscribe_rss: https://your-feedburner-url/

# Homepage
show_excerpts: true  # set to true to show excerpts on the homepage, otherwise full posts are shown

# Comments
# To enable comments, set the `enabled` field to true and supply either a Disqus short name or a Jekyll comments receiver
comments:
  enabled: false
  show_count: false
#  receiver: https://.../  # See https://haacked.com/archive/2018/06/24/comments-for-jekyll-blogs/ for more information.
#  disqus_shortname: YOUR_DISQUS_SHORTNAME

emptyArray: [] # Leave this here.

# haackbar date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
haackbar:
  date_format: "%b %-d, %Y"

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 2 # number of posts per page
page_group_size: 5 # number of pages to group by in the pagination.
paginate_path: "/archive/page/:num"

# Front matter defaults
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
      comments: false
  -
    scope:
      path: "assets/pages"
      type: "pages"
    values:
      layout: page
      comments: false

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-include-cache